---
##############################################################
# Playbook: install.yaml
#
# Sets up Python application to display and log a Temperature
# Measurement on a Raspberry Pi
#
##############################################################

- name: Setup Raspberry Pi services
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - vars/config_common.yml
  vars:
    python_env_wrapper: python-wrapper
    virtual_env: venv
    temp_meas_period: 15.0
    temp_data_dir: "{{ install_dir }}/data"

  tasks:
    - name: Install Python Scripts
      copy:
        src: "{{ item }}"
        dest: "{{ install_dir }}/{{ item | basename }}"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "app/*"

    - name: Install UI Python Scripts
      copy:
        src: "{{ item }}"
        dest: "{{ install_dir }}/ui/{{ item | basename }}"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "app/ui/*.py"

    - name: Install Sensor Python Scripts
      copy:
        src: "{{ item }}"
        dest: "{{ install_dir }}/sensors/{{ item | basename }}"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "app/sensors/*.py"

    - name: Install Services Python Scripts
      copy:
        src: "{{ item }}"
        dest: "{{ install_dir }}/services/{{ item | basename }}"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "app/services/*.py"

    - name: Install application icons
      copy:
        src: app/ui/icons/thermometer-svgrepo-com.svg
        dest: /usr/share/icons/thermometer.svg
        owner: root
        group: root
        mode: 0755

    - name: Install rpi service wrapper
      template:
        src: python_env_wrapper.sh
        dest: /usr/local/bin/{{ python_env_wrapper }}
        mode: 0755
        owner: root
        group: root

    - name: Create monitor shutdown service file
      template:
        src: rpi_monitor.service.j2
        dest: /usr/lib/systemd/system/{{ item.name }}.service
        owner: root
        group: root
        mode: 0755
      loop:
        - {
            name: monitor-shutdown,
            description: Monitor pushbutton to initiate a graceful power-off,
            script: "{{ install_dir }}/services/monitorshutdown.py",
          }

    - name: Create optional service files
      template:
        src: rpi_monitor.service.j2
        dest: /usr/lib/systemd/system/{{ item.name }}.service
        owner: root
        group: root
        mode: 0755
      loop:
        - {
            name: display-ip-addr,
            description: Display IP address,
            script: "{{ install_dir }}/services/monitorip.py",
          }
        - {
            name: temperature-logger,
            description: Log temperature measurements to a local file,
            script: "{{ install_dir }}/main.py --ui tty --period {{ temp_meas_period }}",
          }
      when: run_as_service

    - name: Create desktop file - GUI
      template:
        src: rpi_desktop.j2
        dest: /usr/share/applications/Thermometer.desktop
        owner: root
        group: root
        mode: 0755
      vars:
        desktop_term_enabled: false
        desktop_exec: main.py
        desktop_name: "Thermometer"
